version: "3.1"
services:

  server:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
  client:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      # - PGADMIN_ENABLE_TLS=null
    volumes:
      - pgadmin4:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5480:80"

volumes:
  pgdata:
  pgadmin4:
